theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins
title: Logic + Machine Learning
description: Website showcasing our projects that are at the intersection of logic and machine learning
show_downloads: false
